# Generated by Django 6.0.3 on 2026-03-09 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_donations', models.IntegerField(default=0)),
                ('total_meals_saved', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('active_donors', models.IntegerField(default=0)),
                ('active_ngos', models.IntegerField(default=0)),
                ('active_volunteers', models.IntegerField(default=0)),
                ('total_pickups_completed', models.IntegerField(default=0)),
                ('food_waste_prevented_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('co2_emissions_saved', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('average_pickup_time_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('average_delivery_time_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pickup_success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('delivery_success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('volunteer_participation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ngo_satisfaction_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LocationAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('total_donations', models.IntegerField(default=0)),
                ('total_meals_saved', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('active_ngos', models.IntegerField(default=0)),
                ('high_demand_areas', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'city'],
                'unique_together': {('date', 'city')},
            },
        ),
        migrations.CreateModel(
            name='FoodCategoryAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_donations', models.IntegerField(default=0)),
                ('average_safety_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('waste_prevented_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.foodcategory')),
            ],
            options={
                'ordering': ['-date', 'category'],
                'unique_together': {('date', 'category')},
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='analytics_u_user_id_54ee7d_idx'), models.Index(fields=['activity_type', 'timestamp'], name='analytics_u_activit_f59ac3_idx')],
            },
        ),
    ]
